// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cdczljsfuwofibeamknh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkY3psanNmdXdvZmliZWFta25oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyNzYyMjgsImV4cCI6MjA1Nzg1MjIyOH0.fzoqxvyblTgvRqJVy-WzRhYkrYAbiKMdpGZiUDMwFP8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);